filebeat.inputs:
- type: log
  enabled: true
  paths:
   - /opt/elasticsearch_training/ch7/demo_shop.log
  tags: ["demo_shop","shop_info"]

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true

setup.template.settings:
  index.number_of_shards: 3

setup.kibana:
  host: "localhost:5601"

output.logstash:
  hosts: ["localhost:5144"]
